- .github/workflows/pr-check.yaml
Since we moved to the podman-desktop organisation, we share the workers for the github action
> chore: adding concurrency rule

- packages/frontend/src/lib/empty-screen/EmptyQuadletList.spec.ts
- packages/frontend/src/lib/empty-screen/EmptyQuadletList.svelte
- packages/frontend/src/pages/QuadletsList.svelte
Specify that the selected container engine is not running (if it is not)
Specify that no container engines is running (if none are running)
> feat: better empty quadlet list page

- packages/backend/src/services/podman-service.spec.ts
- packages/backend/src/services/podman-service.ts
Fixes https://github.com/podman-desktop/extension-podman-quadlet/issues/221
> fix: ssh command should specify the connection name

- packages/backend/package.json
- packages/frontend/package.json
- pnpm-lock.yaml
- tests/playwright/package.json
The e2e use the api version to define which podman-desktop should be downloaded to run the e2e.
https://github.com/podman-desktop/extension-podman-quadlet/blob/382771c28ad5ef0066d947e2dc48771485f696a3/.github/workflows/pr-check.yaml#L119-L123
So we need to update everything at once, otherwise tests will fail
> chore: bump @podman-desktop/* to 1.16.0

- .github/workflows/pr-check.yaml
- linter & format & typecheck do not need to run in the os-matrix, running them on ubuntu only
- keep the os-matrix for unit tests.
> refactor: simplify pr-check

- .github/workflows/pr-check.yaml
Devising e2e test by 2, on windows going from 8m to 4m.
In this repository we do not use upstream version of Podman Desktop, we take the `@podman-desktop/api` version and download the corresponding archive.
Therefore for most of pr-check the workflow is the same 
1. Download podman desktop
2. Install Podman Desktop packages
3. Build Podman Desktop  
This 3 steps were taking half the time, let's cache them. (This is what this PR is adding).
The reason why https://github.com/podman-desktop/extension-podman-quadlet/pull/131 were failing is because I failed to understand that playwright was caching the browsers outside the repository. After getting this information, I configured it to cache inside the repo, so it is included in the cached archive.
Fixes …
> feat: trying e2e cache (again)

- .github/dependabot.yml
- packages/frontend/package.json
- packages/frontend/postcss.config.cjs
- packages/frontend/src/app.css
- packages/frontend/src/lib/buttons/RadioButtons.svelte
- packages/frontend/vite.config.js
- pnpm-lock.yaml
Copy of https://github.com/podman-desktop/extension-bootc/pull/1238
Adding a dependabot rules to upgrade tailwindcss all together since we have `@tailwindcss/vite` and `tailwindcss` which seems to be in sync
> chore: migrate tailwindcss to v4

- packages/shared/src/messages/constants.ts
Fixes https://github.com/podman-desktop/extension-podman-quadlet/issues/249
> fix: adding QuadletApi#start to noTimeoutChannels

- packages/shared/src/utils/quadlet-type.ts
When working on https://github.com/podman-desktop/extension-podman-quadlet/issues/40 noticed that the `build` quadlet type was missing lead to errors when parsing them (not recognised).
> fix: adding missing quadlet type build

- packages/backend/src/apis/quadlet-api-impl.spec.ts
- packages/backend/src/apis/quadlet-api-impl.ts
- packages/backend/src/models/quadlet.ts
- packages/backend/src/services/quadlet-service.spec.ts
- packages/backend/src/services/quadlet-service.ts
- packages/backend/src/utils/parsers/quadlet-kube-parser.spec.ts
- packages/backend/src/utils/parsers/quadlet-kube-parser.ts
- packages/backend/src/utils/parsers/quadlet-type-parser.spec.ts
- packages/backend/src/utils/parsers/quadlet-unit-parser.spec.ts
- packages/backend/src/utils/parsers/quadlet-unit-parser.ts
- packages/frontend/src/lib/monaco-editor/KubeYamlEditor.spec.ts
- packages/frontend/src/lib/monaco-editor/KubeYamlEditor.svelte
- packages/frontend/src/lib/table/QuadletActions.spec.ts
- packages/frontend/src/pages/QuadletDetails.spec.ts
- packages/frontend/src/pages/QuadletDetails.svelte
- packages/frontend/src/pages/QuadletsList.spec.ts
- packages/frontend/src/utils/quadlet.spec.ts
- packages/frontend/src/utils/quadlet.ts
- packages/shared/src/apis/quadlet-api.ts
- packages/shared/src/messages/constants.ts
- packages/shared/src/models/quadlet-info.ts
Fixes https://github.com/podman-desktop/extension-podman-quadlet/issues/40
Available at `quay.io/rh-ee-astefani/podman-quadlet-prerelease:0.8.0`
> feat: adding kube yaml tab to details page for kube quadlets

- packages/frontend/src/lib/empty-screen/EmptyQuadletList.spec.ts
- packages/frontend/src/lib/empty-screen/EmptyQuadletList.svelte
- packages/frontend/src/pages/QuadletsList.spec.ts
- packages/frontend/src/pages/QuadletsList.svelte
Disable the buttons when no connection are available or when no running connection are found.
Fixes https://github.com/podman-desktop/extension-podman-quadlet/issues/299
> feat(ui): disable buttons when no connections running

- packages/backend/src/services/quadlet-service.spec.ts
- packages/backend/src/services/quadlet-service.ts
Following https://github.com/podman-desktop/extension-podman-quadlet/pull/306 we should only try to get the statuses of quadlet **with an associated** systemd service, moreover only update the statuses of those quadlet.
Fixes https://github.com/podman-desktop/extension-podman-quadlet/issues/311
> fix: systemd service refresh only quadlet with associated service

- packages/backend/src/apis/quadlet-api-impl.spec.ts
- packages/backend/src/apis/quadlet-api-impl.ts
- packages/backend/src/services/quadlet-service.spec.ts
- packages/backend/src/services/quadlet-service.ts
- packages/shared/src/apis/quadlet-api.ts
The `quadlet-api-impl` were still using the `quadlet#id` to start / stop / log systemd service. This PR change this behaviour, to use the `quadlet#service`.
Fixes https://github.com/podman-desktop/extension-podman-quadlet/issues/313
**Manually**
1. Open the quadlet details page
2. go to logs tab
3. click on start
4. assert logs are showing up
> fix(systemd): using quadlet service for start stop and log operation

- tests/playwright/src/model/quadlet-details-page.ts
- tests/playwright/src/model/quadlet-list-page.ts
- tests/playwright/src/quadlet-extension.spec.ts
Enhance the e2e to now include the following scenario
1. Pull `quay.io/podman/hello:latest`
2. Install Podlet
3. Generate Image Quadlet for `quay.io/podman/hello:latest`
4. Assert quadlet is inactive by default
5. Open Quadlet Details
6. Start Image Quadlet
7. Assert `RUNNING`
8. Stop Image Quadlet
9. Assert not `RUNNING`
10. Remove Image Quadlet
11. Assert Quadlet list page is empty
Need rebase after https://github.com/podman-desktop/extension-podman-quadlet/pull/318
Fixes https://github.com/podman-desktop/extension-podman-quadlet/issues/317
- GitHub actions should be ✅
> test(e2e): full create, start, stop, remove scenario

- packages/frontend/src/lib/table/QuadletName.spec.ts
- packages/frontend/src/lib/table/QuadletName.svelte
- packages/frontend/src/pages/QuadletsList.svelte
Quadlet name on the Quadlet list were not clickable, and leading to inconstancies with the Podman Desktop application.
https://github.com/user-attachments/assets/09224b4f-3473-42a2-995a-2de3544ef64c
Fixes https://github.com/podman-desktop/extension-podman-quadlet/issues/217
> feat(QuadletList): make quadlet name clickable

- packages/backend/src/models/quadlet.ts
- packages/frontend/src/lib/table/QuadletStatus.spec.ts
- packages/frontend/src/lib/table/QuadletStatus.svelte
- packages/shared/src/models/quadlet-info.ts
To be able to properly display that a Quadlet is in an invalid state, we should have a dedicated `error` state.
> ℹ️ this PR does not include any logic to set the state to error, a follow-up PR to fix https://github.com/podman-desktop/extension-podman-quadlet/issues/304 will do it.
Part of https://github.com/podman-desktop/extension-podman-quadlet/issues/304
> feat: adding `error` state to Quadlet & QuadletInfo models

- packages/frontend/src/lib/table/QuadletName.svelte
Following https://github.com/podman-desktop/extension-podman-quadlet/pull/327 I noticed that when the quadlet name is using the path, and not the service name (when the Quadlet is in an error state), we have the text that overflow.
**Before**
**After**
> fix(ui): quadlet name column text ellipsis

- packages/backend/src/services/podman-service.ts
- packages/backend/src/services/quadlet-service.spec.ts
- packages/backend/src/services/quadlet-service.ts
- packages/backend/src/utils/parsers/quadlet-dryrun-parser.spec.ts
- packages/backend/src/utils/parsers/quadlet-dryrun-parser.ts
To determine which Quadlet are available in a given connection, we run `/usr/libexec/podman/quadlet -user -dryrun` which output something like the following 
```
---foo-image.service---
<quadlet content>
---bar-image.service---
<quadlet content>
```
```
quadlet-generator[49094]: Loading source unit file /home/axel7083/.config/containers/systemd/foo.image
quadlet-generator[49094]: Loading source unit file /home/axel7083/.config/containers/systemd/bar.image
quadlet-generator[49094]: Loading source unit file /home/axel7083/.config/containers/systemd/hihih-error.image
quadlet-generator[49094]: converting "hihih-error.image": unsupported key 'Annotation' in group 'Image' in /home/axel7083/.config/containers/systemd/hihih-error.image
```
In the stdout, we always have the Quadlet corresponding …
> feat: properly parse quadlet -dryrun stderr

- packages/podlet-js/package.json
- packages/podlet-js/src/images/image-generator.spec.ts
- packages/podlet-js/src/images/image-generator.ts
- packages/podlet-js/src/images/tests/hello-world/expect.ini
- packages/podlet-js/src/images/tests/hello-world/image-inspect.json
- packages/podlet-js/src/images/tests/nginx/expect.ini
- packages/podlet-js/src/images/tests/nginx/image-inspect.json
- packages/podlet-js/src/models/image-quadlet.ts
- packages/podlet-js/src/models/service-quadlet.ts
- packages/podlet-js/src/utils/generator.ts
- pnpm-lock.yaml
Adding `ImageGenerator` to `podlet-js` package: transforming an [ImageInspectInfo](https://podman-desktop.io/api/interfaces/ImageInspectInfo) into an Image Quadlet.
```ts
// should run inside a podman desktop extension
import { ImageGenerator } from 'podlet-js';
import { containerEngine } from '@podman-desktop/api';
async function demo(): Promise<string> {
// Get the image inspect from Podman Desktop api
const imageInfo = await containerEngine.getImageInspect(<engine-id>, <image-id>);
// Use podlet-js ImageGenerator to generate an ImageQuadlet
const generator =  new ImageGenerator({ image: imageInfo });
return generator.generate();
}
```
Part of https://github.com/podman-desktop/extension-podman-quadlet/issues/298
**Details**
In the `packages/podlet-js/src/images/tests` there are several …
> feat(podlet-js): adding image generator

- packages/backend/src/services/podman-service.spec.ts
- packages/backend/src/services/webview-service.spec.ts
- packages/backend/src/services/webview-service.ts
We can simplify the mocking when they only mock `functions` and `classes` to simply the module, vitest will mock all properly.
> chore(backend): cleanup `node:*` mocking

- packages/backend/package.json
- packages/frontend/package.json
- packages/podlet-js/package.json
- pnpm-lock.yaml
- tests/playwright/package.json
Bumping podman-desktop libs to 1.17
- The version of playwright use **must** match the one shipped with `podman-desktop`, so bumping `@playwright/test`
Fixes https://github.com/podman-desktop/extension-podman-quadlet/issues/357
> chore(deps): bump @podman-desktop/* to 1.17

- packages/backend/src/models/quadlet.ts
- packages/backend/src/services/quadlet-service.spec.ts
- packages/backend/src/services/quadlet-service.ts
- packages/backend/src/utils/parsers/quadlet-dryrun-parser.spec.ts
- packages/backend/src/utils/parsers/quadlet-dryrun-parser.ts
- packages/frontend/src/pages/QuadletDetails.spec.ts
- packages/frontend/src/pages/QuadletDetails.svelte
- packages/shared/src/models/quadlet-info.ts
When a Quadlet is in an error state (invalid YAML, invalid property, etc.) it does not have an associated systemd service.
The `Quadlet#content` property corresponds to the systemd generate content, but when the quadlet is in an error state this is undefined.
To better reflect the reality, making the field optional, and nicely handle it.
**Quadlet in Error state**
**Valid Quadlet**
Fixes https://github.com/podman-desktop/extension-podman-quadlet/issues/343
> feat: makes quadlet content optional

- packages/podlet-js/package.json
- packages/podlet-js/src/compose/compose.spec.ts
- packages/podlet-js/src/compose/compose.ts
- packages/podlet-js/src/compose/models/podman-pod.ts
- packages/podlet-js/src/compose/tests/redis/compose.yaml
- packages/podlet-js/src/compose/tests/redis/expect.yaml
- pnpm-lock.yaml
We rely on the Podlet tool to generate the following
- Container Quadlet (alternative implemented through https://github.com/podman-desktop/extension-podman-quadlet/pull/348)
- Image Quadlet (alternative implemented through https://github.com/podman-desktop/extension-podman-quadlet/pull/332)
The last element we need an alternative to remove podlet is the compose generation: this PR introduce a very basic compose generator.
Required for https://github.com/podman-desktop/extension-podman-quadlet/issues/298
In the same way testing has been implemented for containers and image generator.
In the `packages/podlet-js/src/compose/tests` there are several folders; the structure of each folder in it is the following
```
.
└── tests/
└── <test-case>/
├── expect.yaml
├── compose.yaml
```
The file …
> feat(podlet-js): adding basic compose logic

- packages/podlet-js/src/index.ts
Following https://github.com/podman-desktop/extension-podman-quadlet/pull/406, adding missing export for the `Compose` class.
> fix(podlet-js): adding missing export

- .github/workflows/pr-check.yaml
Following discussion with @odockal , the podman-desktop folder can be excluded, in fact we only interested in two folder, the `tests/playwright/output` (html result) and the `tests/playwright/tests` (video and configuration)
Fixes https://github.com/podman-desktop/extension-podman-quadlet/issues/420
> fix(e2e): exclude podman-desktop folder from artifact

- .github/workflows/release.yaml
Since `podlet-js` package has been added, and the e2e, the release.yaml has not been updated.
Required for 
- https://github.com/podman-desktop/extension-podman-quadlet/issues/278
> chore(workflow): update release.yaml

- README.md
Following https://github.com/podman-desktop/extension-podman-quadlet/pull/439 adding the coverage badge to the README
> docs(README): adding coverage badge

- .github/workflows/pr-check.yaml
As per requested in https://github.com/podman-desktop/extension-podman-quadlet/pull/416#discussion_r2020478226 updating the pr-checks in a separate PR.
> Currently packages are independent, so we do not need to build before running typecheck and unit tests. However, with https://github.com/podman-desktop/extension-podman-quadlet/pull/416 the `backend` packages will depends on `podlet-js` and typecheck will fails as no type are available if the package is not built.
Required for
- https://github.com/podman-desktop/extension-podman-quadlet/issues/298
> chore(pr-check): update workflow with build step

- .github/workflows/pr-check.yaml
- packages/backend/package.json
- packages/backend/src/services/container-service.spec.ts
- packages/backend/src/services/container-service.ts
- packages/backend/src/services/image-service.spec.ts
- packages/backend/src/services/image-service.ts
- packages/backend/src/services/podlet-js-service.spec.ts
- packages/backend/src/services/podlet-js-service.ts
- pnpm-lock.yaml
Creating `PodletJsService` which will replace (in a near future hopefully :crossed_fingers: ) the existing `PodletCliService`
> :information_source: the code is independent and not exposed to the user, therefore no breaking change
- Adding podlet-js as dependencies of the backend
- Adding build step in CI (since we need to have podlet-js built) to run typescheck etc.
Part of https://github.com/podman-desktop/extension-podman-quadlet/issues/298
> feat(backend): create `PodletJsService`

- .github/workflows/pr-check.yaml
This may help reducing the number of jobs running on the organisation
> chore(workflows): enable fail fast strategy

- packages/backend/src/apis/quadlet-api-impl.spec.ts
- packages/backend/src/models/quadlet.ts
- packages/backend/src/services/quadlet-service.spec.ts
- packages/backend/src/utils/parsers/quadlet-dryrun-parser.ts
- packages/backend/src/utils/parsers/quadlet-unit-parser.spec.ts
- packages/backend/src/utils/parsers/quadlet-unit-parser.ts
- packages/frontend/src/lib/monaco-editor/KubeYamlEditor.spec.ts
- packages/frontend/src/lib/table/QuadletActions.spec.ts
- packages/frontend/src/lib/table/QuadletName.spec.ts
- packages/frontend/src/lib/table/QuadletStatus.spec.ts
- packages/frontend/src/pages/QuadletDetails.spec.ts
- packages/frontend/src/pages/QuadletsList.spec.ts
- packages/frontend/src/utils/quadlet.spec.ts
- packages/shared/src/models/quadlet-info.ts
Quadlets can depends on each other, meaning `foo.container` could defined `bar.image` as its image, giving a direct link between those two.
Thankfully, the Quadlet generator gave us this information inside the `[Unit]` section of the generated Quadlet. We can simply parse it.
First part of https://github.com/podman-desktop/extension-podman-quadlet/issues/427 (backend part)
You can check the full branch to see the full feature  [axel7083#feature/quadlet-require/full](https://github.com/axel7083/extension-podman-quadlet/tree/feature/quadlet-require/full)
> feat(backend): parse quadlets requires

- packages/frontend/src/App.svelte
- packages/frontend/src/lib/monaco-editor/MonacoEditor.spec.ts
- packages/frontend/src/lib/monaco-editor/MonacoEditor.svelte
- packages/frontend/src/lib/monaco-editor/monaco-environment.ts
- packages/frontend/src/lib/monaco-editor/monaco.spec.ts
- packages/frontend/src/lib/monaco-editor/monaco.ts
- packages/frontend/vite.config.ts
Supersede https://github.com/podman-desktop/extension-podman-quadlet/pull/490 - enable dynamic import for monaco editor by removing all static import.
Creating a `MonacoManager` class being the only responsible of the import of the monaco module.
⚠️ Vitest has a particularity, if you do `vi.mock(<module>)`, it will import the module and mock the content => for monaco this is bad, the module is very big. If we provide a factory, `vi.mock(<module>, () => ({}))` it don't import the module => good.
Fixes https://github.com/podman-desktop/extension-podman-quadlet/issues/489
- Ensure that the monaco editor is accessible
> refactor(monaco): import once, use many

- packages/backend/src/apis/dialog-api-impl.ts
- packages/backend/src/services/dialog-service.spec.ts
- packages/shared/src/apis/dialog-api.ts
- packages/shared/src/models/input-box-options.ts
Exposing `showInformationMessage` and `showInputBox` to the frontend.
Required for
- https://github.com/podman-desktop/extension-podman-quadlet/issues/424
> feat(RPC): update DialogAPI  & implementation

- pnpm-lock.yaml
merging a lot of dependabot PRs introduced a duplicated entry in the lock file, removing that duplicated entry
> chore: remove duplicated entry in lock file

- packages/backend/src/apis/quadlet-api-impl.ts
- packages/backend/src/services/quadlet-service.ts
- packages/backend/src/utils/telemetry-events.ts
- packages/frontend/src/lib/forms/compose/QuadletComposeForm.svelte
- packages/frontend/src/lib/forms/quadlet/QuadletGenerateForm.svelte
- packages/frontend/src/pages/QuadletDetails.svelte
- packages/shared/src/apis/quadlet-api.ts
- packages/shared/src/messages/constants.ts
- tests/playwright/src/model/quadlet-generate-page.ts
- tests/playwright/src/quadlet-extension.spec.ts
Two function in the `QuadletAPI` doing almost the same things 
- `saveIntoMachine` which save quadlets
- `updateIntoMachine` which update quadlets
While working on https://github.com/podman-desktop/extension-podman-quadlet/issues/424 I had to create a new function, doing what the previous two were doing, but again slightly differently.
Let's save myself some sanity, and factorise all of them into a single `writeIntoMachine`.
**Manually**
1. generate a Quadlet from an existing image / container
2. assert it is nicely created and listed
> refactor(Quadlets): factorise `saveIntoMachine` and `updateIntoMachine`

- packages/backend/src/services/main-service.spec.ts
- packages/backend/src/services/podman-service.spec.ts
- packages/backend/src/services/quadlet-service.spec.ts
- packages/backend/src/services/webview-service.spec.ts
- packages/backend/src/utils/logger-impl.spec.ts
- packages/backend/tsconfig.json
- packages/backend/vitest.config.ts
- packages/backend/vitest.setup.spec.ts
- packages/backend/vitest.setup.ts
In the `packages/backend/**.spec.ts` files the `@podman-desktop/api` is often mocked the same way. Let's create a dedicated `vitest.setup.ts` doing the mocking of what we need.
> chore(vitest): create `vitest.setup.ts` file

- packages/backend/src/services/provider-service.ts
- packages/backend/src/services/quadlet-service.ts
- packages/backend/src/services/routing-service.ts
- packages/backend/src/utils/publisher.spec.ts
- packages/backend/src/utils/publisher.ts
The `Publisher` class notify the webview with content provided by the class extending it; however in some cases other class may want to be notified, not only the webview.
For example, in https://github.com/podman-desktop/extension-podman-quadlet/pull/535 the `PodmanService` need to refresh its cache if any provider changes: it should listener for the `ProviderService` event.
> feat(backend): make Publisher uses EventEmitter

- packages/backend/package.json
- packages/backend/vite.config.ts
- pnpm-lock.yaml
Required for https://github.com/podman-desktop/extension-podman-quadlet/issues/515, adding the [ssh2](https://www.npmjs.com/package/ssh2) package to the dependencies.
- Nothing really to test
> chore(deps): adding `ssh2` package

- packages/backend/src/utils/remote/podman-ssh.spec.ts
- packages/backend/src/utils/remote/podman-ssh.ts
This PR adds a `PodmanSSH` class taking an SSHConfig as argument. This very nice class expose an `exec` method, very similar to `{@link import('@podman-desktop/api').process.exec}`.
The newly `exec` method expose is similar to `podman machine ssh <machine> <command>`, allowing us to directly exec commands inside the podman machine without using the podman cli (we instead use the ssh connection to the machine).
The goal is to simplify the `PodmanService` class and use the podman machine ssh logic, which does not work for podman remote.
Required https://github.com/podman-desktop/extension-podman-quadlet/issues/515
> feat(backend): create `PodmanSSH` client

- packages/backend/src/utils/worker/podman-worker.ts
`PodmanWorker` is an abstract class with several method; `read`, `write`, `exec` and other handy methods. When dealing a podman connection (either native or remote) the goal is to use a worker instead of the methods in `PodmanService`.
We will have two implementation of PodmanWorker:
- `PodmanNativeWorker`: on linux deals with native podman
- `PodmanSSHWorker`: deals with Podman Machines and remote through SSH
Having such abstract logic allow us to simplify the code, and reduce coupling. 
Required https://github.com/podman-desktop/extension-podman-quadlet/issues/515
> feat(backend): create PodmanWorker abstract class

- packages/backend/package.json
- packages/backend/src/utils/remote/podman-sftp.spec.ts
- packages/backend/src/utils/remote/podman-sftp.ts
- pnpm-lock.yaml
Very similar to https://github.com/podman-desktop/extension-podman-quadlet/pull/545 the PodmanSFTP (Or Podman Secure File Transfer Protocol) is a handy class allowing us to interact with the filesystem of a podman machine.
The Quadlet extension need to `read`, `write` files inside the Podman Machine, currently it is **super hacky**, I used `podman machine ssh <connection> cat <path>` to read file from stdout.
This is not really nice, and there are alternative. Podman always come with an ssh connection to the machines, and we can use that to establish a secure file transfer protocol between the machine and us.  
The amazing [ssh2-sftp-client](https://www.npmjs.com/package/ssh2-sftp-client) package based on `ssh2` allow us to do that.
Required …
> feat(backend): create `PodmanSFTP` client

- packages/backend/src/utils/remote/podman-ssh.ts
- packages/backend/src/utils/worker/podman-ssh-worker.spec.ts
- packages/backend/src/utils/worker/podman-ssh-worker.ts
Same as https://github.com/podman-desktop/extension-podman-quadlet/pull/561, but SSH workers, not native.
> Workers are used to interact with a given Podman Connection
> feat(backend): adding ssh podman worker 

- packages/backend/src/utils/worker/podman-native-worker.spec.ts
- packages/backend/src/utils/worker/podman-native-worker.ts
Following (https://github.com/podman-desktop/extension-podman-quadlet/pull/547) adding `PodmanWorker` abstract class, here is the first implementation, the `PodmanNativeWorker`.
This PR is a part of https://github.com/podman-desktop/extension-podman-quadlet/pull/535 and is required for https://github.com/podman-desktop/extension-podman-quadlet/issues/515.
> The full feature can be tested in https://github.com/podman-desktop/extension-podman-quadlet/pull/535
> feat(backend): adding native podman worker

- packages/backend/src/services/main-service.ts
- packages/backend/src/services/podlet-js-service.spec.ts
- packages/backend/src/services/podlet-js-service.ts
- packages/backend/src/utils/telemetry-events.ts
Following https://github.com/podman-desktop/extension-podman-quadlet/issues/298 the telemetry events related to Podlet has been removed, those included 
- PODLET_INSTALL
- PODLET_VERSION
- PODLET_GENERATE
- PODLET_COMPOSE
The two first should be removed, but the two last should be re-implemented.
Fixes https://github.com/podman-desktop/extension-podman-quadlet/issues/508
Required for https://github.com/podman-desktop/extension-podman-quadlet/issues/578
> feat(podlet-js): adding telemetry events

- .github/workflows/release.yaml
- Containerfile
Following investigation in https://github.com/podman-desktop/extension-podman-quadlet/issues/583, I can't find a nice way to use vite to bundle the ssh2 package: manually copying it is the only way I have to make it works...
> :information_source: I know @benoitf you don't like `--squash-all` this is a temporary solution, I want to introduce as minimal change for now :)
> fix(Containerfile): hard copy ssh2 package & deps

- packages/podlet-js/src/compose/compose.ts
- packages/podlet-js/src/compose/tests/nginx/compose.yaml
- packages/podlet-js/src/compose/tests/nginx/expect.yaml
Fixes https://github.com/podman-desktop/extension-podman-quadlet/issues/601
> fix(podlet-js): compose generate port parsing order

- packages/backend/src/services/systemd-service.spec.ts
- packages/backend/src/services/systemd-service.ts
While investigating https://github.com/podman-desktop/extension-podman-quadlet/issues/585, the problem only occurs on certain machine, on my machine I was not seeing any issue, on MacOS (AppleHV & Libkrun) and Linux QEMU the problem was visible through high duration time for starting services.
> feat(systemd): adding duration to telemetry

- packages/podlet-js/src/compose/compose.ts
- packages/podlet-js/src/compose/models/podman-pod.ts
- packages/podlet-js/src/compose/tests/environments/compose.yaml
- packages/podlet-js/src/compose/tests/environments/expect.yaml
I have not put much effort into the `Compose => Kube YAML` of the `podlet-js` framework. Let's add some basic feature support.
**Manually**
You cannot test it, through the UI it is broken (ref https://github.com/podman-desktop/extension-podman-quadlet/issues/586)
> feat(podlet-js): support converting compose service with env

- packages/backend/src/services/quadlet-service.ts
- packages/backend/src/utils/worker/podman-worker.spec.ts
- packages/backend/src/utils/worker/podman-worker.ts
Thanks to @gastoner testing, we captured a regression when migrating to the worker system.
Fixes https://github.com/podman-desktop/extension-podman-quadlet/issues/613
> fix(worker): handle quadlet exec run error

- packages/frontend/src/lib/forms/quadlet/QuadletGenerateForm.spec.ts
- packages/frontend/src/lib/forms/quadlet/QuadletGenerateForm.svelte
Prevent users from generating invalid quadlet by providing an invalid name; (E.g. when generating Container quadlet, the filename must be `*.container`).
> We could discuss UX, but I would rather first have this to be merge, as a safeguard, then improve the design later one.
https://github.com/user-attachments/assets/c6f4179a-15aa-4e30-8e78-1874715bc7d4
Fixes https://github.com/podman-desktop/extension-podman-quadlet/issues/612
**Manually**
1. checkout PR
2. start Podman Desktop
3. Go to Quadlet webview
4. Go to `Generate Quadlet`
5. Select any Quadlets
6. Try to type something in the input
7. assert only validated value are allowed (Load Into Machine would be disabled)
> feat(form): validate quadlet filename

- packages/backend/src/utils/remote/connection-handler.spec.ts
- packages/backend/src/utils/remote/connection-handler.ts
Once disposed, we should **not** call the `connect()` method again.
Fixes https://github.com/podman-desktop/extension-podman-quadlet/issues/645
> fix(ssh): prevent reconnect after disposing

- package.json
The `svelte-check` command was ran from the root directory, using the `tsconfig.ts` from the root, where it should be using the one from `packages/frontend/tsconfig.ts`
Fixes the linter check in https://github.com/podman-desktop/extension-podman-quadlet/pull/717
> fix(scripts): use proper base directory for svelte-check

- package.json
Feel like the https://github.com/podman-desktop/extension-podman-quadlet/pull/724 is failing with the following error
```
Scope: all 19 workspace projects
 ERR_PNPM_LOCKFILE_CONFIG_MISMATCH  Cannot proceed with the frozen installation. The current "patchedDependencies" configuration doesn't match the value found in the lockfile
Update your lockfile using "pnpm install --no-frozen-lockfile"
```
Is probably link to the pnpm version used
> chore(pnpm): update to 10.12.6

- packages/frontend/src/pages/QuadletsList.svelte
Fix for #757 - The search term uses the service name not the container ID to match
> fix: search by quadlet name not id

- packages/frontend/src/pages/QuadletsList.spec.ts
- packages/frontend/src/pages/QuadletsList.svelte
Following https://github.com/podman-desktop/extension-podman-quadlet/pull/758, we search by service name, however in some cases the quadlet may not have corresponding service.
We should instead use the path, which is always defined.
> feat(frontend): filter quadlet based on path

- packages/frontend/src/lib/table/QuadletActions.spec.ts
- packages/frontend/src/lib/table/QuadletActions.svelte
The remove dialog was showing the UUID instead of the service path.
Fixes https://github.com/podman-desktop/extension-podman-quadlet/issues/799
> fix(frontend): deletion dialog

- .github/workflows/pr-check.yaml
Since node 22.18, the Type stripping is enabled by default (ref https://nodejs.org/en/blog/release/v22.18.0#type-stripping-is-enabled-by-default)
Playwright have some issue with it, using solution from https://github.com/microsoft/playwright/issues/34263#issuecomment-3173890500
> chore(e2e): set `--no-experimental-strip-types` flag for playwright

- packages/backend/src/apis/quadlet-api-impl.spec.ts
- packages/backend/src/apis/quadlet-api-impl.ts
Fixes https://github.com/podman-desktop/extension-podman-quadlet/issues/448
Image to test ` quay.io/rh-ee-astefani/podman-quadlet-prerelease:1756467344`
---
Need confirmation that journalctl logs are accessible in KDE
> fix(journalctl): remove unnecessary DBUS_SESSION_BUS_ADDRESS env
