packages/frontend/src/lib/forms/quadlet/QuadletGenerateForm.svelte
packages/frontend/src/lib/monaco-editor/MonacoEditor.svelte
packages/frontend/src/pages/QuadletDetails.svelte

feat: monaco editor support dark mode

---

packages/backend/src/apis/logger-api-impl.ts
packages/backend/src/apis/quadlet-api-impl.ts
packages/backend/src/extension.ts
packages/backend/src/services/logger-service.ts
packages/backend/src/services/main-service.ts
packages/backend/src/services/podman-service.spec.ts
packages/backend/src/services/podman-service.ts
packages/backend/src/utils/logger.ts
packages/frontend/package.json
packages/frontend/src/api/client.ts
packages/frontend/src/lib/forms/quadlet/children/ContainerQuadletForm.svelte
packages/frontend/src/lib/terminal/XTerminal.svelte
packages/frontend/src/lib/terminal/terminal-theme.ts
packages/frontend/src/pages/QuadletDetails.svelte
packages/frontend/src/stores/logger-store.ts
packages/shared/src/apis/logger-api.ts
packages/shared/src/apis/quadlet-api.ts
packages/shared/src/messages.ts
pnpm-lock.yaml

For quadlet available on the podman native, displaying the logs using journalctl

feat: logs support for quadlet with podman native 📜

---

packages/backend/src/apis/quadlet-api-impl.ts
packages/backend/src/services/logger-service.ts
packages/backend/src/utils/logger.ts
packages/frontend/src/pages/QuadletDetails.svelte
packages/shared/src/apis/quadlet-api.ts

dispose the logger, and kill the associate process when leaving the page

feat: improve logger lifecycle

---

packages/backend/package.json
packages/backend/src/apis/podlet-api-impl.ts
packages/backend/src/services/main-service.ts
packages/backend/src/services/podlet-cli-helper.ts
packages/backend/src/services/podlet-cli-service.spec.ts
packages/backend/src/services/podlet-cli-service.ts
packages/backend/src/services/podman-service.ts
packages/frontend/src/lib/forms/QuadletComposeForm.svelte
packages/frontend/src/lib/forms/quadlet/QuadletGenerateForm.svelte
packages/frontend/src/lib/forms/quadlet/children/ContainerQuadletForm.svelte
packages/frontend/src/lib/forms/quadlet/children/ImageQuadletForm.svelte
packages/frontend/src/lib/forms/quadlet/quadlet-utils.ts
packages/frontend/src/lib/select/ContainerProviderConnectionSelect.svelte
packages/shared/src/apis/podlet-api.ts
packages/shared/src/models/run-result.ts

1. Improve windows support when dealing with multiple connections
2. Support rootful connection
3. improve error message in the generate and compose form

feat(podlet): support multi connection support

---

packages/backend/src/apis/quadlet-api-impl.ts
packages/backend/src/services/main-service.ts
packages/backend/src/services/quadlet-helper.ts
packages/backend/src/services/quadlet-service.ts
packages/frontend/src/pages/QuadletsList.svelte
packages/frontend/src/stores/synchronisation.ts
packages/shared/src/apis/quadlet-api.ts
packages/shared/src/messages/MessageProxy.spec.ts
packages/shared/src/messages/MessageProxy.ts
packages/shared/src/models/synchronisation.ts

feat: better synchronisation management

---

packages/backend/src/apis/podlet-api-impl.ts
packages/backend/src/extension.ts
packages/backend/src/services/main-service.ts
packages/backend/src/services/podlet-cli-helper.ts
packages/backend/src/services/podlet-cli-service.spec.ts
packages/backend/src/services/podlet-cli-service.ts
packages/backend/src/services/quadlet-helper.ts
packages/backend/src/services/quadlet-service.ts
packages/backend/src/services/systemd-helper.ts
packages/backend/src/services/systemd-service.spec.ts
packages/backend/src/services/systemd-service.ts
packages/backend/src/utils/telemetry-events.ts

Adding telemetry to Podman Quadlet extension

feat: init telemetry 📎

---

tests/playwright/src/quadlet-extension.spec.ts

Following https://github.com/podman-desktop/extension-podman-quadlet/pull/165 the e2e were failing

fix(e2e): fix extension label

---

packages/backend/src/models/quadlet.ts
packages/backend/src/services/quadlet-helper.ts
packages/backend/src/services/quadlet-service.spec.ts
packages/backend/src/services/quadlet-service.ts
packages/backend/src/utils/parsers/quadlet-unit-parser.ts
packages/frontend/src/lib/empty-screen/EmptyQuadletList.svelte
packages/frontend/src/lib/table/QuadletActions.svelte
packages/frontend/src/lib/table/QuadletStatus.svelte
packages/shared/src/models/quadlet-info.ts

Fixes 
- https://github.com/podman-desktop/extension-podman-quadlet/issues/208
- https://github.com/podman-desktop/extension-podman-quadlet/issues/209

refactor: improve connection object management & state management

---

tests/playwright/src/quadlet-extension.spec.ts

Fixes https://github.com/podman-desktop/extension-podman-quadlet/issues/207

fix(e2e): monaco flaky test

---

packages/backend/src/services/provider-service.spec.ts
packages/backend/src/services/provider-service.ts

Fixes https://github.com/podman-desktop/extension-podman-quadlet/issues/218

feat: exclude non-podman provider

---

packages/backend/src/apis/quadlet-api-impl.ts
packages/backend/src/services/quadlet-service.spec.ts
packages/backend/src/services/quadlet-service.ts
packages/backend/tsconfig.json
packages/frontend/src/lib/forms/compose/QuadletComposeForm.svelte
packages/frontend/src/pages/QuadletCompose.svelte
packages/frontend/src/pages/QuadletsList.spec.ts
packages/frontend/src/pages/QuadletsList.svelte
packages/shared/src/apis/quadlet-api.ts

Allowing bulk deletion
Fixes https://github.com/podman-desktop/extension-podman-quadlet/issues/176
**Manually**
1. Create a lot of quadlets
2. Select all
3. Click on the trash icon
4. assert all are being deleted

feat: better table 

---

.github/workflows/pr-check.yaml
packages/backend/src/services/podman-service.spec.ts
packages/backend/src/services/podman-service.ts
tests/playwright/src/quadlet-extension.spec.ts

Make e2e run on windows runner
Fixes https://github.com/podman-desktop/extension-podman-quadlet/issues/233
- `line 8: wget: command not found` (wget is not installed on windows runner??): replacing with curl
- Everything is so slow on windows (increasing all timeouts, like timeout everywhere)
- Podman is not installed on windows runners: so installing + podman machine init
- Extract podman build step to a dedicated a singleton step (avoid repeating the same build on each os)

feat: enable e2e windows

---

Containerfile
package.json

all build image are failing. Updating corepack in the Containerfile fix the issue, also updating pnpm

fix(corepack): signature issue

---

packages/backend/src/services/quadlet-service.spec.ts
packages/backend/src/services/quadlet-service.ts

https://github.com/podman-desktop/extension-podman-quadlet/pull/312 fixed partially the problem, but it was still occurring.
Fixes https://github.com/podman-desktop/extension-podman-quadlet/issues/311

fix: systemd statuses update

---

.github/workflows/pr-check.yaml
package.json
packages/backend/package.json
packages/frontend/package.json
pnpm-lock.yaml
tests/playwright/package.json

Similar to https://github.com/podman-desktop/extension-bootc/pull/1436

chore: bump node to v22

---

.github/workflows/coverage.yml

Publishing vitest coverage to GitHub page.
Here is what it will look like https://axel7083.github.io/extension-podman-quadlet (this is on my fork)

chore(ci): create coverage workflow

---

packages/backend/src/utils/logger-impl.spec.ts

Noticed through codecov that the LoggerImpl class has no coverage.

test(logger-impl): ensuring class is covered

---

.github/workflows/release.yaml

Fixes https://github.com/podman-desktop/extension-podman-quadlet/issues/435

chore(workflow): update GITHUB_TOKEN for release.yaml

---

packages/backend/src/services/command-service.spec.ts

Noticed through codecov that the CommandService class has no coverage.

test(command-service): ensuring class is covered

---

package.json

podlet-js package was missing when running typecheck.

chore(typecheck): adding missing check for podlet-js

---

packages/backend/src/services/podman-service.spec.ts

The function `isMachineRootful` (see bellow) was not covered by any tests.
https://github.com/podman-desktop/extension-podman-quadlet/blob/67df48d9b25420cead41889ec608b94cda394407/packages/backend/src/services/podman-service.ts#L272
Required for
- https://github.com/podman-desktop/extension-podman-quadlet/issues/512

test(podman-service): ensuring `isMachineRootful` is covered

---

.github/workflows/coverage.yml
.github/workflows/release.yaml

Use the same ubuntu version for all runners.
Fixes https://github.com/podman-desktop/extension-podman-quadlet/issues/580
Required for https://github.com/podman-desktop/extension-podman-quadlet/issues/578

fix(workflows): consistent ubuntu version

---

packages/backend/src/apis/quadlet-api-impl.ts
packages/backend/src/assets/templates.json
packages/backend/src/services/quadlet-service.spec.ts
packages/backend/src/services/quadlet-service.ts
packages/shared/src/apis/quadlet-api.ts
packages/shared/src/models/template.ts

Introducing Quadlet templates
Part of https://github.com/podman-desktop/extension-podman-quadlet/issues/424

feat: introduce templates

---

.github/workflows/coverage.yml
packages/backend/package.json
packages/backend/vite.config.ts
packages/frontend/package.json
packages/frontend/vite.config.ts
packages/podlet-js/package.json
packages/podlet-js/vite.config.ts
pnpm-lock.yaml

Enable bundle analysis, I am curious to have those metrics, I think this would be nice to see if this metrics is useful, and if it is, maybe we should consider https://github.com/podman-desktop/podman-desktop/issues/12161 or revert it
Fixes https://github.com/podman-desktop/extension-podman-quadlet/issues/719

chore(codecov): enable bundle analysis

---

packages/backend/src/apis/quadlet-api-impl.ts

A refactoring of the checks done on the quadlet to avoid to forget if we add another check later.
Follow-up of https://github.com/podman-desktop/extension-podman-quadlet/pull/783

refactor(backend): check logic in function
